### ISSUE TITLE
add duplicity/duply

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#48]
On the client first create directories `/root/.duply/duply-client`
````
# grep -v \# conf 
GPG_KEY="$(cat /root/root.gpgkey)"
GPG_PW='vagrant'
GPG_OPTS='--trust-model always'
TARGET='sftp://root@server//root/backup'
SOURCE='/'
MAX_AGE=1
MAX_FULL_BACKUPS=1
MAX_FULLS_WITH_INCRS=1
VERBOSITY=5
TEMP_DIR=/tmp

# cat exclude
/sys
/proc
````
And, on the server create directory `/root/backup`. Run a check:
````
[root@client duply-client]# echo yes | duply duply-client status
Start duply v1.11.3, time is 2017-12-11 20:53:01.
Using profile '/root/.duply/duply-client'.
Using installed duplicity version 0.7.13.1, python 2.7.5, gpg 2.0.22 (Home: ~/.gnupg), awk 'GNU Awk 4.0.2', grep 'grep (GNU grep) 2.20', bash '4.2.46(2)-release (x86_64-redhat-linux-gnu)'.
Autoset found secret key of first GPG_KEY entry '07CE8E6D' for signing.
Checking TEMP_DIR '/tmp' is a folder and writable (OK)
Test - Encrypt to '07CE8E6D' & Sign with '07CE8E6D' (OK)
Test - Decrypt (OK)
Test - Compare (OK)
Cleanup - Delete '/tmp/duply.11990.1513021981_*'(OK)

--- Start running command STATUS at 20:53:01.939 ---
Using archive dir: /root/.cache/duplicity/duply_duply-client
Using backup name: duply_duply-client
Import of duplicity.backends.acdclibackend Succeeded
Import of duplicity.backends.azurebackend Succeeded
Import of duplicity.backends.b2backend Succeeded
Import of duplicity.backends.botobackend Succeeded
Import of duplicity.backends.cfbackend Succeeded
Import of duplicity.backends.dpbxbackend Failed: No module named dropbox
Import of duplicity.backends.gdocsbackend Succeeded
Import of duplicity.backends.giobackend Succeeded
Import of duplicity.backends.hsibackend Succeeded
Import of duplicity.backends.hubicbackend Succeeded
Import of duplicity.backends.imapbackend Succeeded
Import of duplicity.backends.lftpbackend Succeeded
Import of duplicity.backends.localbackend Succeeded
Import of duplicity.backends.mediafirebackend Succeeded
Import of duplicity.backends.megabackend Succeeded
Import of duplicity.backends.multibackend Succeeded
Import of duplicity.backends.ncftpbackend Succeeded
Import of duplicity.backends.onedrivebackend Succeeded
Import of duplicity.backends.par2backend Succeeded
Import of duplicity.backends.pydrivebackend Succeeded
Import of duplicity.backends.rsyncbackend Succeeded
Import of duplicity.backends.ssh_paramiko_backend Succeeded
Import of duplicity.backends.ssh_pexpect_backend Succeeded
Import of duplicity.backends.swiftbackend Succeeded
Import of duplicity.backends.sxbackend Succeeded
Import of duplicity.backends.tahoebackend Succeeded
Import of duplicity.backends.webdavbackend Succeeded
ssh: Connected (version 2.0, client OpenSSH_7.4)
ssh: Authentication (publickey) successful!
ssh: [chan 0] Opened sftp connection (server version 3)
Main action: collection-status
================================================================================
duplicity 0.7.13.1 (June 18, 2017)
Args: /bin/duplicity collection-status --name duply_duply-client --encrypt-key 07CE8E6D --sign-key 07CE8E6D --verbosity 5 --gpg-options --trust-model always sftp://root@server//root/backup
Linux client.box 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64
/bin/python2 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
================================================================================
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
Collection Status
-----------------
Connecting with backend: BackendWrapper
Archive dir: /root/.cache/duplicity/duply_duply-client

Found 0 secondary backup chains.
No backup chains with active signatures found
No orphaned or incomplete backup sets found.
Using temporary directory /tmp/duplicity-IMxnCl-tempdir
--- Finished state OK at 20:53:02.601 - Runtime 00:00:00.662 ---
````

**Comment by gdha** [comment]
The recover part fails with duply:
````
++ PASSPHRASE=vagrant
++ duplicity --name duply_duply-client --encrypt-key A1A86DCB --sign-key A1A86DCB --verbosity 5 --gpg-options '--trust-model always' -t now sftp://root@server//root/backup /mnt/local/restore
...
Added incremental Backupset (start_time: Fri Dec 29 10:14:47 2017 / end_time: Fri Dec 29 10:46:53 2017)
Added incremental Backupset (start_time: Fri Dec 29 10:46:53 2017 / end_time: Fri Dec 29 12:02:03 2017)
Added incremental Backupset (start_time: Fri Dec 29 12:02:03 2017 / end_time: Fri Dec 29 14:12:33 2017)
Added incremental Backupset (start_time: Fri Dec 29 14:12:33 2017 / end_time: Fri Dec 29 14:21:09 2017)
Added incremental Backupset (start_time: Fri Dec 29 14:21:09 2017 / end_time: Fri Dec 29 14:28:33 2017)
Added incremental Backupset (start_time: Fri Dec 29 14:28:33 2017 / end_time: Fri Dec 29 14:34:21 2017)
Added incremental Backupset (start_time: Fri Dec 29 14:34:21 2017 / end_time: Fri Dec 29 14:37:12 2017)
Added incremental Backupset (start_time: Fri Dec 29 14:37:12 2017 / end_time: Fri Dec 29 19:06:21 2017)
Added incremental Backupset (start_time: Fri Dec 29 19:06:21 2017 / end_time: Mon Jan  1 07:27:57 2018)
Added incremental Backupset (start_time: Mon Jan  1 07:27:57 2018 / end_time: Mon Jan  1 08:31:23 2018)
Last full backup date: Fri Dec 29 10:14:47 2017
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-full.20171229T101447Z.manifest (3680117)
Found 4 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T101447Z.to.20171229T104653Z.manifest (2164)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T104653Z.to.20171229T120203Z.manifest (3482)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T120203Z.to.20171229T141233Z.manifest (2387)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T141233Z.to.20171229T142109Z.manifest (2243)
Found 1 volumes in manifest
GPG error detail: Traceback (most recent call last):
  File "/bin/duplicity", line 1540, in <module>
    with_tempdir(main)
  File "/bin/duplicity", line 1534, in with_tempdir
    fn()
  File "/bin/duplicity", line 1385, in main
    do_backup(action)
  File "/bin/duplicity", line 1462, in do_backup
    restore(col_stats)
  File "/bin/duplicity", line 728, in restore
    restore_get_patched_rop_iter(col_stats)):
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 558, in Write_ROPaths
    for ropath in rop_iter:
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 521, in integrate_patch_iters
    for patch_seq in collated:
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 389, in yield_tuples
    setrorps(overflow, elems)
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 378, in setrorps
    elems[i] = iter_list[i].next()
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 121, in difftar2path_iter
    tarinfo_list = [tar_iter.next()]
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 344, in next
    self.set_tarfile()
  File "/usr/lib64/python2.7/site-packages/duplicity/patchdir.py", line 332, in set_tarfile
    assert not self.current_fp.close()
  File "/usr/lib64/python2.7/site-packages/duplicity/dup_temp.py", line 227, in close
    assert not self.fileobj.close()
  File "/usr/lib64/python2.7/site-packages/duplicity/gpg.py", line 297, in close
    self.gpg_failed()
  File "/usr/lib64/python2.7/site-packages/duplicity/gpg.py", line 264, in gpg_failed
    raise GPGError(msg)
GPGError: GPG Failed, see log below:
===== Begin GnuPG log =====
===== End GnuPG log =====


GPGError: GPG Failed, see log below:
===== Begin GnuPG log =====
===== End GnuPG log =====
````
then it hangs forever... try the same on the command line:
````
# /sbin/duplicity --name duply_duply-client --encrypt-key A1A86DCB --sign-k
ey A1A86DCB --verbosity 5 --gpg-options "--trust-model always" -t now sftp://root@server//root/backup /mnt/local/restore
Using archive dir: /root/.cache/duplicity/duply_duply-client
Using backup name: duply_duply-client
...
Added incremental Backupset (start_time: Fri Dec 29 19:06:21 2017 / end_time: Mon Jan  1 07:27:57 2018)
Added incremental Backupset (start_time: Mon Jan  1 07:27:57 2018 / end_time: Mon Jan  1 08:31:23 2018)
Last full backup date: Fri Dec 29 10:14:47 2017
PASSPHRASE variable not set, asking user.
GnuPG passphrase: 
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-full.20171229T101447Z.manifest (3680117)
Found 4 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T101447Z.to.20171229T104653Z.manifest (2164)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T104653Z.to.20171229T120203Z.manifest (3482)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T120203Z.to.20171229T141233Z.manifest (2387)
Found 1 volumes in manifest
Processing local manifest /root/.cache/duplicity/duply_duply-client/duplicity-inc.20171229T141233Z.to.20171229T142109Z.manifest (2243)
Found 1 volumes in manifest
Killed

````
-> suspect it waits on the pass-phrase entry, however, the **killed** is not very promising.
-> seems the `/tmp` is running full

What **not** seems to work is:
````
# export TEMP_DIR=/temp
# duply duply-client status
Start duply v1.11.3, time is 2018-01-01 15:25:32.
Using profile '/root/.duply/duply-client'.
Using installed duplicity version 0.7.13.1, python 2.7.5, gpg 2.0.22 (Home: ~/.gnupg), awk 'GNU Awk 4.0.2', grep 'grep (GNU grep) 2.20', bash '4.2.46(2)-release (x86_64-redhat-linux-gnu)'.
Autoset found secret key of first GPG_KEY entry 'A1A86DCB' for signing.
Checking TEMP_DIR '/tmp' is a folder and writable (OK)
````

**Comment by gdha** [comment]
The problem we had all the time after most common issues were fixed with `duply` was https://bugs.launchpad.net/duplicity/+bug/1518650 the signing key was not the **pub** but the **sub** key (very confusing stuff) during _restore_.
Issue https://github.com/rear/rear/issues/1664 contain some fixes after my tests.

**Comment by gdha** [comment]
https://github.com/rear/rear/issues/1668#issuecomment-354538672 is still a requirement to handle with ansible. Has been added as an extra task:  [rear-test : trust the GPG key (for duplicity)]

**Comment by gdha** [comment]
successful test performed - logs are at https://gist.github.com/4f383510463e4c058d49da5d4ff7cf0d
